version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout

      - run:
          name: Run main.rs
          command: cargo run

workflows:
  version: 2
  Abc Latest Bot:
    triggers:
      - schedule:
          cron: "00 12 * * 5" # 毎週金曜日21時(JST)に実行
          filters:
            branches:
              only:
                - master

    jobs:
      - build:
          context: AbcBot
